export default {
  cards: {
    Insensitive: {
      title: 'Insensitive',
      tag: 'MBTI ESFP',
      showText: 'The data from your answers suggest you match our <b><span class="character-color">Insensitive Personality Profile</span></b>.  Generally, you seem to keep yourself to yourself, preferring your own company, which can appear nonchalant or uncaring to others.  You may find it hard to communicate and interact with other people, sometimes finding hard to see how they are thinking or feeling.  Unfamiliar situations or social events may cause you anxierty or be upsetting and you may even perfer calm and restful environments to noisy or loud.  You probably enjoy familiarity in tasks you do to constant changing tasks or roles.  This can make you seem challeging to others but you have a sensistive side too.',
      value: [3, 0],
    },
    Aloof: {
      title: 'Aloof',
      tag: 'MBTI ESTP',
      showText: 'Although to others you may seems engaging and interactive, privately, you tend not to be interested in having many social relationships, preferring a more sheltered, private lifestyle.  We classify this type of personality as the <b><span class="character-color">Aloof Personality Profile</span></b>.  It can seem as if you are observing the world from outside rather than participating in it and your beliefs may differ from the mainstream.   You may even feel a lack of direction in life and perhaps you have a vivid imagination and imagine fantasy worlds.  It may be that you feel like you are "acting" rather than being yourself and, sometimes, you can be eloquent and others inarticulate.  It could also be that your outward appearance may even contradict what you are really feeling.  Some may say you are uncaring or apathetic but, inside, you have many creative and original moments as well as deeply, or even passionately, enjoing certain areas of interest to you.',
      value: [3, 2],
    },
    Apathetic: {
      title: 'Apathetic',
      tag: 'MBTI ISTJ',
      showText: 'As an <b><span class="character-color">Apathetic Personality Type</span></b>, you appear to be a reserved or quiet person, perhaps withdrawn or uninvolved.  It can also appear to be a lack of energy or enthusiam for things.  You may find yourself having diificulty being stirred into action, preferring to let things pass by and just observe.  People may call you "indifferent" but you could just prefer the familiar or status quo.  To others, you may also appear uncaring but you may just be undecided, hestitant or uncertain and want to be more certain before becoming more involved.',
      value: [3, 4.15],
    },
    Discreet: {
      title: 'Discreet',
      tag: 'MBTI ISTP',
      showText: 'You might have heard people use the concept of the “wallflower”—a popular flowering plant that tends to grow in the cracks and gaps of stone walls—as a way to describe others. People who are “wallflowers” might quite literally stand against the walls at parties or social gatherings rather than socialize with others. Our data indicate that you fit the <b><span class="character-color">Discreet Personality Profile</span></b> Wallflower personality profile. In short, you are introverted, humble, and unassuming, but you don’t shy away from getting into the detials of getting things done - you’re a hard worker.  People fitting the <b><span class="character-color">Discreet</span></b> Wallflower personality profile show lower levels of extraversion in several areas. Unsurprisingly, they aren’t as likely to find the company of others as stimulating or rewarding as doing activities on their own. They lead slower-paced lives. Wallflowers don’t require high levels of stimulation to be happy. They are less impulsive than their peers, less likely to try new activities and experience different things. Wallflowers tend to be more sensitive to what others think of them. When it comes to difficult or unpleasant tasks, you exercise higher levels of self-discipline and willpower to persist until they are completed. You think before you act, you are good at carefully analyzing situations from multiple angles before taking action.',
      value: [3.15, 6.15],
    },
    Compassionate: {
      title: 'Compassionate',
      tag: 'MBTI ESTJ',
      showText: 'Having a <b><span class="character-color">Compassionate Personality Profile</span></b> means you are very agreeable, adapting to others because you focus on them.  This may be in contrast to your view on the external world where you are less likely to concentrate your attention.  Some may even think you are introverted if they saw you as you see yourself.  You are somewhat focussed on results and like to get things done but are aware how others are feeling while you are doing that, trying to fit with others and meet your goals at the same time; in short, you are responsive to others\' needs.  In terms of focus, you are neither focussed on the future or past but on the present both a work and personally which suggests you live in the moment.',
      value: [2.85, 5.85],
    },
    Eccentric: {
      title: 'Eccentric',
      tag: 'MBTI ESFJ',
      showText: 'You appear to be an <b><span class="character-color">EccentricPersonality Profile</span></b>.  We think it means that that you are easily worried by events.  Your well-being is dependent on your surroundings and events and you can fell uneasy or troubled by what is going on around you. Feeling slightly stressed or tense is normal for you and many things trouble you.  This can lead to agitation and low -level frustration with the world or specific people.  Specifically, you tend to emotionally react to circumstances rather than assessing their significance first.  Because of your character, you tend to be inward-looking, worry about how you are feeling and may appear to be uncaring or indifferent to thers.  This combination of traits can also make you appear to be introverted or even disagreeable.',
      value: [4, 0],
    },
    Suspicious: {
      title: 'Suspicious',
      tag: 'MBTI INTJ',
      showText: 'Our analysis suggest you are a <b><span class="character-color">Suspicious Personality Profile</span></b>.  Delusion, dread, anxiety, feel oppressed, persecution complex, misconceived reality, fantasy, dream, illusion.  Sometimes you feel the world is against you or that  can\'t please anyone or genuinely oppressed.  Your view of the world may not align with the majority and that disconnection may you feel anxious and stressed, perhaps even fill you with dread.  Many world and personal events may seem to have many clandetine explanations or secretive plots and all these things may combine to make you feel your ideas or views are better than others.  You may also view the otherwise innocent or friendly actions as hostile and so bear grudges for a long time.',
      value: [4, 1],
    },
    'Self-critical': {
      title: 'Self-critical',
      tag: 'MBTI INTP',
      showText: 'As the name suggests, <b><span class="character-color">Self-critical Personalities Profile</span></b> are hard on themselves.  They things they do as worthless and themselves as insignificant without justification and when the reality may well be different.  These traits can make them feel a combination of gloomy, miserable, unhappy or troubled when the reality is actually likely to be different.  The pessimism can lead to a negative cycle of judgmental thoughts that can manifest as cynicism and make otherwise positive situations look and feel bleak.  However, the negative thoughts general stem from not accepting the reality of a situation and, once things more in perspective, things can seem brighter.',
      value: [4, 3.15],
    },
    Anxious: {
      title: 'Anxious',
      tag: 'MBTI ENFP',
      showText: 'We think <b><span class="character-color">Anxious Personality Types</span></b> rely on others when it comes to making decisions.  They are very agreeable in that they adapt to the company they are in but aren\'t confident in expressing their thoughts.  They may feel pressure in decision-making situations which makes them defer to others.   This can lead to over-reliance on others and a sense of isolation and loneliness when alone.  The lack of confidence means that Anxious Types can also be pessimistic and reaction to changing circumstances rather than assessing the situation in a more calm way.  By delegating a lot of decision making and responsibility to others, together with being introvert, can make Anxious Personality Types appear passive.',
      value: [4.15, 4.15],
    },
    Perfectionist: {
      title: 'Perfectionist',
      tag: 'MBTI ENTJ',
      showText: 'This type is another that is self-explanatory; The <b><span class="character-color">Perfectionist Persoanlity Type</span></b> want everything to be just right!   They are very conscientious and extrememly focussed on getting the "right" result.  This means that they can be slightly reactive to situations, especially when things aren\'t as they expected. This excessive focus can be unecceasrily time-consuming and somewhat stressful, especially when the Anxious person doesn\'t get the outcome they expect.  They also have a tendency to prefer how things were (when they were perfect) so new, uncertain and likely imperfect future events.  Perfectionist are willing to negotiate to achieve as "perfect" outsome as possible.',
      value: [3.85, 3.85],
    },
    Determined: {
      title: 'Determined',
      tag: 'MBTI ENTP',
      showText: 'Your levels of personality traits most closely match our <b><span class="character-color">Determined Personality Profile</span></b>. You are determined, logical, grounded—your mind seems to be built for making decisions. When intrusive thoughts or worries enter your mind, you don’t spend too much time on them. On the flipside, you may have less access to and awareness of your own feelings. You find familiarity in logic and routines, more so than the average person. Because of this preference for logic and routine, you might find yourself much less prone than others to worry. You’re great at handling stress. You’re known for being level-headed, not only through stressful times of crisis, but also through the ups and downs experienced by your friends, family, and colleagues. In these situations, you lead with certainty and stability where others may act in panic and confusion. For you, strong cravings and urges have less of an effect on you than others; you are willing to sacrifice short-term satisfaction for long-term goals.',
      value: [4, 7],
    },
    Procrastinator: {
      title: 'Procrastinator',
      tag: 'MBTI ENFJ',
      showText: 'You are a <b><span class="character-color">Procrastinator Personality Type</span></b>.  You see yourself as a moderator, committing to neither on side or another and also nonchalant, not caring about the outcome in a particular situtation.  On the other side, you can be challenging and reactive but, generally speaking, <b><span class="character-color">Procrastinator Personailty Types</span></b> appear neutral in situations and that\'s what make they type they are.  Procrastinators are reactive to situations but their reactions tend to come from an inner monologue that says "no" to things, which appears to others like they can\'t make a decision when asked.  The indecisiveness in Procrastinators mean they tend to moderate conflicts to subconsciously keep things unchanged and often appear as unconcerned with events.  Another way of Procrastinating is simply not to participate and hope the decision goes away which can appear to others as being a reserved person.',
      value: [5, -1],
    },
    Isolated: {
      title: 'Isolated',
      tag: 'MBTI ISFJ',
      showText: 'You are an <b><span class="character-color">Isolated Persoanlity Type</span></b> and you see yourself as inquisitive and interested but you can be introverted. Additionally, you can be a negotiator in social situations but you do with sensitivity as tht is a trait.  Isolated Personalites can feel social anxiety which sadly leads to feelings of inhibition, inadequacy and inferiority.  Isolated Types can also be sensitivity to the negative comments of others and and so make them avoid social interaction. They often avoid social relationships with others unless they are certain they will be accepted because they often consider themselves to be socially inept or personally unappealing.  In these situations, they fear being ridiculed, humiliated, rejected, or disliked.',
      value: [5, 2.85],
    },
    Humble: {
      title: 'Humble',
      tag: 'MBTI ISFP',
      showText: 'Have you ever been called humble, forgiving—even a saint? Because our data seems to indicate that you’re pretty close to one being a <b><span class="character-color">Humble Personality Profile</span></b>! You are exceptionally agreeable in all areas of your personality. You’re known for giving others the benefit of the doubt more often than the average person—you tend to assume that most people are fair, honest, and have good intentions. You are more likely than others to take people as they are, to trust that they have good intentions—to forgive and forget. You are more altruistic than most other people, you likely care deeply about improving the lives of others. You’re a prime example of humility and modesty. In meetings, you might even downplay your accomplishments. You give off a feeling of warmth when speaking with others. People closely matching the Humble Personality Profile are deeply in touch with their feelings, though this may lead to excessive self-consciousness. ',
      value: [5, 5],
    },
    Responsible: {
      title: 'Responsible',
      tag: 'MBTI INFJ',
      showText: 'People with the <b><span class="character-color">Responsible Personality Profile</span></b> are dutiful, self-disciplined, and deliberate. In other words, you have a stronger sense of duty and obligation than most. When it comes to difficult or unpleasant tasks, you exercise higher levels of self-discipline and willpower to persist until they are completed. While you can be quite the introvert at times, your inward-looking personality is quite a strength. You think before you act, you are good at carefully analyzing situations from multiple angles before taking action. At the same time, you come off as a genuinely nice person. There’s a good chance that you’re unassuming and humble. You are more likely than others to take people as they are, to trust that they have good intentions—to forgive and forget. You are likely to show honesty more than most: you believe in telling the truth when dealing with others and are therefore candid and genuine. Indeed, you find helping others to be truly rewarding.',
      value: [5, 6],
    },
    Active: {
      title: 'Active',
      tag: 'MBTI INFP',
      showText: 'The <b><span class="character-color">Active Personality Profile</span></b> sees themselves a moderator but you can be ambivelent and apathetic.  On the other hand, you can be challenging with a reactive side.    Active Personality types can be inattentive and restless which can be disruptive the balance in social situations as can their impulsivity.  As will all personality types, there are varying degrees within each type but, at extreme levels, these behaviours can cause strain on relationships, both at home and work.  It may seem to others as if you are forgetful, not listening or even disorganised.  Some in this type may find it hard to start tasks, making them appear lazy or ambivalent, and then not finish them, giving the appearance of impulsively starting tasks.  The reluctance to start tasks due to a lack of focus can also appear to be challenging to those setting the task.',
      value: [6, -2],
    },
    Unsatisfied: {
      title: 'Unsatisfied',
      tag: 'MBTI INFP',
      showText: '<b><span class="character-color">Unsatisified Personality Types</span></b> see themselves mainly as a preserver of status quo and nonchalant.  Unsatisfied personality types have patterns of behavior that sabotages their goals. They may often avoid or undermine pleasurable experiences, be drawn to situations or relationships in which they will suffer.  Frustratingly, they may prevent others from helping them.  They unconsciously choose people and situations that lead to disappointment, failure, or mistreatment even when better options are clearly available.  Following positive personal events, Unsatisfied Personality types can respond with depression, guilt, or a behavior that reduces the pleasure of the achievement.  They can provoke responses from others and then feel hurt, defeated, or humiliated.  Unsatisified Personality Types  can reject opportunities for pleasure or reluctantly enjoy activities.  Failing to accomplish tasks crucial to their personal objectives, despite having demonstrated ability to do so, or being unterested in/rejecting people who consistently treat them well are behaviours Unsatisfied personalities recognise as it excessive self-sacrifice that is unsolicited by the intended recipients of the sacrifice.',
      value: [6, 2],
    },
    Neutral: {
      title: 'Neutral',
      tag: 'MBTI INFP',
      showText: 'You won\'t be surprised to learn that the <b><span class="character-color">Neutral Personality Profile</span></b> scores in the personality categories as the name sugegsts - average.  This doesn\'t mean you are average.  You are a negotiator when dealing with others and perfectly balance your conscientiousness between highyl foccussed and nonchanlant.  You are responsive to your emotions, neither being over reactive or resilient while your focus on the world exterior to you is ambivalent - dead-centre between extraverted and intraverted.  Lastly, you 6live int he moment - you do not focus on the past or the future overly.',
      value: [6, 3],
    },
    Productive: {
      title: 'Productive',
      tag: 'MBTI INFP',
      showText: 'As a <b><span class="character-color">Productive Personality Type</span></b>, you see yourself as inquisitive and interested. Additionally, you can be adversarial but with a resilient side.  As a Productive Personality, you are resilient to setbacks, perserving to get things done inspite of setbacks. To acheive your goals, you can be determined even it is means ruffling a few feathers of those around you and you appear not too bothered about upsetting them either!  The task is everything and there isn\'t much room for feelings.  By being task-orientated, you can withdraw into your own world and appear reserved but it\'s just your focus dominating the task.  Productive Personality Type focus on the new and innovation rather the current or past state of affairs.',
      value: [6, 4],
    },
    Calm: {
      title: 'Calm',
      tag: 'MBTI INFP',
      showText: 'The way you answered suggests that you have <b><span class="character-color">Calm Personality Profile</span></b>; a moderator and focussed. Additionally, you are flexible which allows you stay calm in different situations.  Calm personalities are, as you might expect, unruffled by life\'s chaos.  They remain serene and swan-like throughout it all.  Being adaptable to change and others\' behaviours, the Calm personality accomodates change well.  Some of that may be due to the focus that Calm Personalities have, which is high compare to average.  Being a centred type of personality, neither being overtly extraverted or introverted, adds to the charateristics of being Calm.  You score highly on resilience which means that you can deal with setbacks easily without losing your placid, calm persona.',
      value: [6, 8],
    },
    Unemotional: {
      title: 'Unemotional',
      tag: 'MBTI INFP',
      showText: 'People with Unemotional Personality Profiles, such as you, see themselves as moderators and nonchalant in social situations. Being an Unemotional personality type can be difficult.  it means you have the tendency to be impulsive that could, at times, be seem as irresponsible.  Extreme variants of the Unemotional personality type are often combative, manipulative or calculating.  They show little empathy and are unemotional, hence the name type.  This means that realtionships can be difficult for Unemotional type; social norms do not come naturally to them and neither does remorse for their actions.  They tend to be extroverted and live in the moment, neither looking forward or backwards at consequences and appear uncaring, so much so that they can challenge almost everything giving the appearance of doing so for the sake of challenging.  ',
      value: [7, 0],
    },
    'Self-centred': {
      title: 'Self-centred',
      tag: 'MBTI INFP',
      showText: 'The <b><span class="character-color">Self-centred Personality Profile</span></b> is another difficult type to associate with.  Self-centred types have a grandiose sense of self-importance and a preoccupation with fantasies of unlimited success, power, brilliance, beauty, or ideal love.  They can believe that they are in someway special and can only be understood by, or associate with, special people or institutions and have a need for excessive admiration from others.  They can also have a sense of entitlement to special treatment.  A lack of empathy with, and envy of others, together with arrogant or haughty attitudes from Self-centred types means that they have the ability to exploit others as they down-play others value relative to their own.',
      value: [7, 1],
    },
    Positive: {
      title: 'Positive',
      tag: 'MBTI INFP',
      showText: 'The <b><span class="character-color">Positive Personality Profile</span></b> is resislinet to life\'s setbacks.  They see the good in every situation and are uplifting people to be around as they can support an indidual or team through dark times.  They are adapatble and agreeable enough to get along with people but not so much that they accept negative attitudes without a challenge.  Positive people live in the moment, neither dwelling on the past or worrying about the future.  They care just enough about results so as to make them effective but not so much that the result is everything and so open themselves up to disappointment if not met. Positive people are also focus enough on their exterior world enough to be social but they don\'t let it dominate their lives.',
      value: [7, 7],
    },
    Impulsive: {
      title: 'Impulsive',
      tag: 'MBTI INFP',
      showText: 'Your answers determined that you are what we classify as a <b><span class="character-color">Impulsive Personality Profile</span></b>.  The extreme form of this type includes traits such as emotional instability, distorted patterns of thinking or what we are know as "cognitive distortions", impulsive behaviour that cross over into the type of relationships they have.   Impulsive types often feel extreme emotions such as rage, sorrow, shame, panic and longer-term feeling of emptiness and loneliness.',
      value: [8, -1],
    },
    Autonomous: {
      title: 'Autonomous',
      tag: 'MBTI INFP',
      showText: 'Your responses most closely match the <b><span class="character-color">Autonomous Personality Profile</span></b> and it seems you were born to lead.  People might describe you as confident, bold, and determined because you enjoy taking decisive action so much so that you may have a tendency to make decisions for those around you. Handling stress , particularly in emergency situations, and taking rejection are something you do better than the average person. People who fit the Autonomous profile don’t like sticking to set rules. They tend to be leaders in groups. While they might not be the most modest, people matching this profile are less likely to let the opinions of others get in the way of decision-making. Some may argue this makes them more objective decision-makers. In fast-paced working environments and in daily life, they are less susceptible to the effects of anxious thoughts and emotions.',
      value: [8.15, 2.15],
    },
    Patient: {
      title: 'Patient',
      tag: 'MBTI INFP',
      showText: 'Our data indicate that you most closely match <b><span class="character-color">Patient Personality Profile</span></b>. People might describe you as laid-back, creative, and free-spirited. The defining personality trait of the Patient type is opennes - the extent to which a person is open to experiencing new things or activities. You have quite high levels of this trait, compared to the average person.  In addition to being more eager than average to new experiences, you are more aware of your feelings and how to express them. You are relatively less prone to worry; you tend to feel more calm and self-assured than those around you. Compared to your peers you are open to, and are intrigued by, new ways of thinking and novel ideas; you like exploring your surroundings. Sometimes your openness gets in the way of self-control and organization, but this only boosts your creativity.',
      value: [7.85, 1.85],
    },
    Optimistic: {
      title: 'Optimistic',
      tag: 'MBTI INFP',
      showText: 'The <b><span class="character-color">Optimistic Personality Profile</span></b> or Optimist are emotionally resilient in that they respond to their emotions but do not react impulsively.  They control their feelings and so can bounce back from negative feelings.  They are not so results-orientated that it dampens the Optimist\'s spirit because by putting weight not achieving their goals can lead to disappointment.  They may not be the best person to drive a task to completion but they will think anything possible and they share that infectious spirit with others.  The Optimist does not feel the need to adapt or challenge their surroundings: the Optimist says "it\'s good as it is".',
      value: [8, 3.85],
    },
    trusting: {
      title: 'Trusting',
      tag: 'MBTI INFP',
      showText: 'By having a <b><span class="character-color">Trusting Personality Profile</span></b>, you might find that more people than average trust you with their problems for one simple reason: you are a highly agreeable person. You give others the benefit of the doubt more often than the average person - you tend to assume that most people are fair, honest, and have good intentions. People with your personality profile are often called tenderminded, which suggests that many of your judgements and attitudes could be determined by emotion. While some may see this as a problem, this particular tendency makes you a more compassionate decision-maker and confidant. Because you are sincere and honest in your interactions with others, it isn’t very surprising that people feel comfortable confiding in you. Not only are you warm and approachable, but you are also slow to hold grudges against others. You are a team player, predisposed to think about how your actions impact others rather than how they impact yourself. You are likely more open to what others have to say, especially from those who hold different social, political, or religious values. ',
      value: [8, 5],
    },
    Practical: {
      title: 'Practical',
      tag: 'MBTI INFP',
      showText: 'With a <b><span class="character-color">Practical Personality Profile</span></b>, you crave order and stability more than most. You are more level-headed and in control of your emotions than others, especially in chaotic, high-pressure situations. When negative thoughts enter your head, you don’t spend too much time on them. Similarly, you’re less likely to have unhealthy concern for how others think about you. Day-to-day, you are focused, determined to finish the task at hand. You may even find yourself so focused at times that you “do” things without much extra thought, as people with your personality profile tend to have high levels of certainty. To be clear, being a Practical type which craves order and stability, doesn’t necessarily mean that you’re a cold and unapproachable person. On the contrary, your personality profile indicates you are particularly outgoing, sociable, and talkative. You are more affectionate, gentle, and warm than the average person. You’re an order-oriented leader, but you don’t shy away from being enthusiastic and upbeat.',
      value: [8, 6],
    },
    Lively: {
      title: 'Lively',
      tag: 'MBTI INFP',
      showText: 'The <b><span class="character-color">Lively Personality Profile</span></b> loves being the centre of attention.  They want others to approve of them and try their best to win others over.  You will recognise Lively people at a party: they are in the "life and sole".  They can be dramatic, vivacious, enthusiastic and even flirtatious.  Sometimes, this gregariousness can be inappropriate and Lively people can exagerate these behaviours.  Lively types focus on the new and exciting, appear not to be too concerned with things, adapt to their social surrounding in an excitable manner but, as you might expect, mostly focus on what is going on around them.',
      value: [9.15, 0.15],
    },
    Harsh: {
      title: 'Harsh',
      tag: 'MBTI INFP',
      showText: '<b><span class="character-color">Harsh Personality Profiles</span></b> can be seem ruthless.  They can lack empathy and so don\'t understand the extreme negative effects of behavious like bullying, demeaning, manipulation or even abuse.  Not being able to empathise with others\' feeling removes a filter to socially acceptable behaviour.  Harsh people challenge most things which can seem like obnoxious behaviour.  They seem unmoved by targets or results, appearing above it all.  Harsh people are in touch with their emotionals but they neither react impulsively to them nor are they resilient to negative emotions either.  The neutrality of their own emotions means Harsh types focus a lot on their exterior worlds and, to some extent, exploring new things.',
      value: [8.85, -0.2],
    },
    Uninhibited: {
      title: 'Uninhibited',
      tag: 'MBTI INFP',
      showText: 'The <b><span class="character-color">Unhibited Personality Profile</span></b> usual experience a wide emotional range from persistent periods of disinhibition and euphoria that will be noticeable from their normal state by others.  Uninhibited people could experience a decerase in the need for sleep, an overall increase in energy, unusual behaviors and actions, and other more noticeable things to others such as an increase in talkativeness and confidence, together a flight of creative ideas; ideas tend to fall out of the Unhibited. They want to focus on the new and not the past but  they are generally emtionally stable.  The Unhibited tend negotiate well with others so their outpouring of ideas isn\'t usually associated with obnoxiousness.',
      value: [9, 1.85],
    },
    Engaged: {
      title: 'Engaged',
      tag: 'MBTI INFP',
      showText: 'Your answers indicate that your profile most closely matches the <b><span class="character-color">Engaged Personality Profile</span></b>. Much like the coach of a sports team, you’re probably known for your assertive, outgoing, and eager personality. You show elevated levels of extraversion in all areas of your personality. First, you love being around other people, attending social gatherings, perhaps being the life of the party. You can’t seem to get away from the excitement of crowds. Compared to your peers, you may find yourself easily bored without high levels of social or mental stimulation. For this reason, you enjoy the thrill of new activities and experiences. You’re more positive and cheerful than average. At work or among friends, you’re more likely to take charge, to make decisions for others. People matching the Engaged profile tend to be leaders in groups. While they might not be the most modest, they are less likely to let what others think of them get in the way of decision-making. They hold up quite well to stress, particularly in emergency situations.',
      value: [9, 2.85],
    },
    Sociable: {
      title: 'Sociable',
      tag: 'MBTI INFP',
      showText: 'As a people person at heart, you genuinely enjoy spending your time being with others and others love being around you.  People matching the <b><span class="character-color">Sociable Personality Profile</span></b> have a wider capacity to experience positive feelings such as happiness, optimism, enthusiasm, and joy. This emotional knack for positivity reflects a more general self-awareness of your own feelings - a key component of being an effective leader. It’s no surprise, then, that friends and colleagues are drawn to you by your warmth and high social energy. In the workplace, you enjoy leading others and acting decisively. Your calendar outside work is probably full, too: given your Sociable profile, you are more likely to live a fast-paced and busy life. You’re more open than most to filling this limited time with new experiences. Your love of the fast lane comes at a cost, though—you might find yourself growing easily bored without high levels of social or mental stimulation. Your social talent, positivity, and hunger for novelty make it clear that you’re an Entrepreneur.',
      value: [9, 4],
    },
    Outgoing: {
      title: 'Outgoing',
      tag: 'MBTI INFP',
      showText: 'An <b><span class="character-color">Outgoing Personality Profile</span></b> are very outgoing as well as being moderately open to new ideas, focussed and adaptable.  Outgoing types are likely to like doing deals and the whole process associated with negotiating as that fits the components of their personality well.  They like to negotiate being more adaptive than average, focussed on results but not overly so and resilient emotionally so not taking challenging behaviour too personally.',
      value: [9, 5],
    },
  },
};
